version: '3.8'

services:
  portfolio:
    image: jekyll/jekyll:latest
    volumes:
      - .:/srv/jekyll
    ports:
      - "4000:4000"     
      - "35729:35729"   #Allows the live-reload WebSocket to connect to Windows
    command: bash -c "gem install webrick && jekyll serve --livereload --host 0.0.0.0"